bedroom_choices = {
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10
}

price_choices = {
    '100000': '₹10,00,000',
    '200000': '₹20,00,000',
    '300000': '₹30,00,000',
    '400000': '₹40,00,000',
    '500000': '₹50,00,000',
    '600000': '₹60,00,000',
    '700000': '₹70,00,000',
    '800000': '₹80,00,000',
    '900000': '₹90,00,000',
    '1000000': '₹1Cr+',
}

# state_choices = {
#     'AK': 'Alaska',
#     'AL': 'Alabama',
#     'AR': 'Arkansas',
#     'AS': 'American Samoa',
#     'AZ': 'Arizona',
#     'CA': 'California',
#     'CO': 'Colorado',
#     'CT': 'Connecticut',
#     'DC': 'District of Columbia',
#     'DE': 'Delaware',
#     'FL': 'Florida',
#     'GA': 'Georgia',
#     'GU': 'Guam',
#     'HI': 'Hawaii',
#     'IA': 'Iowa',
#     'ID': 'Idaho',
#     'IL': 'Illinois',
#     'IN': 'Indiana',
#     'KS': 'Kansas',
#     'KY': 'Kentucky',
#     'LA': 'Louisiana',
#     'MA': 'Massachusetts',
#     'MD': 'Maryland',
#     'ME': 'Maine',
#     'MI': 'Michigan',
#     'MN': 'Minnesota',
#     'MO': 'Missouri',
#     'MP': 'Northern Mariana Islands',
#     'MS': 'Mississippi',
#     'MT': 'Montana',
#     'NA': 'National',
#     'NC': 'North Carolina',
#     'ND': 'North Dakota',
#     'NE': 'Nebraska',
#     'NH': 'New Hampshire',
#     'NJ': 'New Jersey',
#     'NM': 'New Mexico',
#     'NV': 'Nevada',
#     'NY': 'New York',
#     'OH': 'Ohio',
#     'OK': 'Oklahoma',
#     'OR': 'Oregon',
#     'PA': 'Pennsylvania',
#     'PR': 'Puerto Rico',
#     'RI': 'Rhode Island',
#     'SC': 'South Carolina',
#     'SD': 'South Dakota',
#     'TN': 'Tennessee',
#     'TX': 'Texas',
#     'UT': 'Utah',
#     'VA': 'Virginia',
#     'VI': 'Virgin Islands',
#     'VT': 'Vermont',
#     'WA': 'Washington',
#     'WI': 'Wisconsin',
#     'WV': 'West Virginia',
#     'WY': 'Wyoming'
# }

state_choices = {
    'DL': 'Delhi',
    'MU': 'Mumbai',
    'BL': 'Banglore',
    'CN': 'Chennai',
    'KL': 'Kolkata',
    'JP': 'Jaipur',
    'PJ': 'Panji',
    'HD': 'Hyderabad',
    'PT': 'Patna',
    'PU': 'Pune',
    'BP': 'Bhopal',
    'AM': 'Amritsar',
    'UD': 'Udaipur',
}